version: '3.8'
services:
  app:
    image: jekyll/jekyll:pages
    command: jekyll serve --force_polling
    volumes:
      - $PWD/docs:/srv/jekyll # replace $PWD if necessary.
    ports:
      - 4000:4000
